### ISSUE TITLE
rate limit

### ISSUE THREAD

**Issue by soupnatzi** [techgaun/github-dorks#36]
GitHub Search API rate limit reached

where can i an api token to not get rate limiting?

**Comment by techgaun** [comment]
@soupnatzi we can not really bypass github's rate limits but this library should already be handling and re-running the calls after gracefully waiting for the rate limit to get over. If that's not the case and you still hit rate limits, we should look into it.

**Comment by soupnatzi** [comment]
can we just add a personal token to bypass some rate limiting?i mean i just ran the tool and instantly the rate limit came up?this is just a suggestion

**Comment by techgaun** [comment]
@soupnatzi you should already be able to do that. if you look at readme, you can either specify `GH_TOKEN` (which is your personal access token) or `GH_USER` / `GH_PWD` as environment variables to get the rate limits of authenticated users which is higher than anonymous calls

**Comment by soupnatzi** [comment]
got it thanks for the quick response

**Comment by techgaun** [comment]
sounds good. I am going to close this issue for now. feel free to re-open if there's any issue. thanks
