### ISSUE TITLE
422 Validation Failed

### ISSUE THREAD

**Issue by saikiran7022** [techgaun/github-dorks#41]
GH_TOKEN=************************************************  python3 github-dork.py -u dev-nepal

when iam testing, iam getting this error:-

Scanning User:  dev-nepal
GitHubError encountered on search of dork: filename:.dockercfg auth user:dev-nepal
422 Validation Failed

**Comment by airborne1** [comment]
+1

**Comment by sritarun3** [comment]
+1

**Comment by jh-oliveira** [comment]
+1

**Comment by techgaun** [comment]
@saikiran7022 thanks for opening the ticket. It looks like the above mentioned user does not exist any more. I see this may be an actual issue though given few `+1` in the comments. I'll check tomorrow and try to get a fix out for this.

**Comment by techgaun** [comment]
After looking further, this would happen if the user or the repo in question does not exist. While we could improve the error message, it does not seem like this is a problem for the case when user or repo exists.

**Comment by bigshebang** [comment]
@techgaun are you open to a PR to fix this bug or add other, unrelated features?

**Comment by techgaun** [comment]
@bigshebang definitely open for any enhancements.

**Comment by techgaun** [comment]
Closing this because it happens if provided user/repo don't exist
