### ISSUE TITLE
History files as the dorks

### ISSUE THREAD

**Issue by danielmiessler** [techgaun/github-dorks#6]
How about adding some more local files, for when people accidentally upload their home directory.

So:

- .history
- .bash_history
- etc.

Basically, find all the history files for various shells and put them in there. Should probably include .profile files as well, since people put all sorts of sensitive stuff in there as well.

**Comment by techgaun** [comment]
@danielmiessler good idea. thanks for the addition. Will add such potential ones asap

**Comment by techgaun** [comment]
Added couple of them. I am open for PR :)
