### ISSUE TITLE
Inclusion of Dorks in SecLists

### ISSUE THREAD

**Issue by danielmiessler** [techgaun/github-dorks#7]
Hey there, was wondering if it'd be ok for me to include your dorks file (probably not in the same format) in the SecLists project.

I'm collecting all the different checks of this type into one place so arbitrary engines can query for all of these types of things.

https://github.com/danielmiessler/SecLists/

Thanks!

**Comment by techgaun** [comment]
@danielmiessler sure of course. A mention would be nice but not necessary.
